baseURL: "https://github.com/Zixuan-Hova/aboutMe/"
languageCode: en-us
build:
  writeStats: true
params:
  title: MyPage
  author: Zixuan Li
  description: 
  copyright: >-
    Math Major Survivor  -  Now Fluent in the Language of Numbers
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
              <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="favicon.ico">

  profile:
    name: "Zixuan (Hova) Li."
    tagline: 
    location: "Halifax, NS | Toronto, ON"
    photo: IMG_4987.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/zixuan-li-609898229/"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://github.com/Zixuan-Hova/CampusCodeCraftPy"
        title: GitHub
      
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description:
                 ğŸ‘‹ Hello World! I'm Zixuan (you can call me Hova), a math explorer by training, a data analyst by trade, and an esports enthusiast by choice. I've crunched numbers, gamed late into the night, and turned data into decisions â€” all before my morning coffee.
  experience:
    title: Experiences
    icon: fas fa-briefcase
    list:
      - position: Market Research and Data Analyst Intern
        dates: 2021/04 â€“ 2021/08
        company: Deloitte Foundation
        details: |1-
         
         ğŸ“Š Market Maverick: Dug deep into market trends to boost a charity campaign, impacting lives of over 1,000 beneficiariesâ€”because who says you canâ€™t mix analytics with altruism?
        
         ğŸ“‰ Survey Strategist: Wrangled data from 5,000+ respondents, because making decisions without data is just guessing.
        
         ğŸ“ˆ Content Commander: Spearheaded social media content, boosting engagement by 30%. Turns out, numbers do have real power!



      - position: Front-End Developer Intern
        dates: 2021/01 â€“ 2021/04
        company: ZLSOFT Software Company
        details: |1-
         
         ğŸš€ Tech Trendsetter: Helped pick the coolest tech for web projects, ensuring we were always ahead of the curve.
         
         ğŸ’» CSS Conqueror & JavaScript Juggler: Crafted slick web pages that didnâ€™t just work, they wowed.
         
         ğŸ¤ Collaboration Catalyst: Bridged the gap between front-end flair and back-end brawn, speeding up project delivery by a whopping 20%.
  education:
    title: Education
    icon: fas fa-graduation-cap
    list:
      - degree: Maste of Business Analytics
        college: Saint Mary's University, Sobey School of Business
        thesis_url: "https://www.smu.ca/sobey/mban/"
        dates: 2024/09 - 2025/12
        
      - degree: B.Sc.(Hons) in Mathematics & Its Applications Specialist (Probability/Statistics)
        college: University of Toronto St.George
        dates: 2021/09 - 2024/06
        relevant courses: Time Series Analysis, Multivariate Data Analysis, Observational Studies, Real Analysis, ODE/PDE
        
      - degree: Undergraduate, Computer Science
        college: York University, Lassonde School of Engineering
        dates: 2020/01 - 2020/12
        relevant courses: Theory of Computation, Net-centric Computing, Programming for Mobile Computing
  
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Statistical Analysis of Judicial Decisions, Legal Rules, and Judicial Decision Making
        url: "https://drive.google.com/file/d/1trEixdjbzAI1VU8DbeI4GolzqpG_G5Lr/view?usp=sharing"
        description: |1-
         
         ğŸ•µï¸â€â™‚ï¸ Digging Deep: Armed with Python, R, and SQL, I dive into judicial data, uncovering inefficiencies and disparities that hide in plain sight. Think of me as the detective who uses stats instead of a magnifying glass. |
         
         ğŸ›ï¸ Fighting for Fairness: Using data-driven insights, I highlight case outcome disparities and push for much-needed judicial reforms. It's like being a data-driven superhero, but my cape is made of graphs!
         
         ğŸ” Case Study Spotlight: My deep-dive into bail decisions reveals systemic biases, sparking conversations and paving the way for reform. Itâ€™s not just about finding facts; itâ€™s about making a difference.
      
      - title: Regression Analysis on Graduate Admission
        url: "https://drive.google.com/file/d/14f6Rvhky9cCgkbjQi8ochdrlCOfMHhKs/view?usp=sharing"
        description: |1-
         
         ğŸ“ Predictive Prodigy: Crafted wizard-level regression models to forecast grad school admissions. Who gets in? My algorithms have a guess before they even apply.
         
         ğŸ” Validation Virtuoso: Implemented cross-validation magic to ensure my crystal ball (read: models) wasnâ€™t just spitting out academic gibberish but real, actionable insights.
         
         ğŸ“Š R Aficionado: Went Sherlock Holmes with R, dissecting data layers to spotlight what really sways admission decisions. Spoiler: Itâ€™s more than just grades and test scores.
     
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-cogs
    list:
      - skill: 'Programming Languages (Expert): "Python, R, SQL"'
        skillrating: 95
      - skill: 'Data Analysis (Advanced): "Predictive Modelling, Data Visualization"'
        skillrating: 90
      - skill: 'Web Development (Proficient): "JavaScript, CSS3"'
        skillrating: 85

  hobby:
    title: Hobbies
    icon: fas fa-gamepad
    list:
      - hobby: â›·ï¸ Ski 
      - hobby: ğŸ¾ Tennis
      - hobby: ğŸ® Gaming
      - hobby: Counter-Strike Global Offensive (Premier 15000)
      - hobby: Apex Legends (Diamond)
      - hobby: Valorant (Diamond)
      - hobby: League of Legends (Gold)

